/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
    package coffeshoppp.vistas;
    import coffeshoppp.modelo.Conexion;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;  // Correct placement

/**
 *
 * @author Jonathan's PC
 */
public class frm_productos extends javax.swing.JFrame {

/**
     * Creates new form frm_productos
     */

    private Conexion conexion;
    
    public frm_productos() {
        initComponents();
        
        combobox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebida", "Postre", "Snack" }));
        
        btn_modificar_producto.setVisible(false);
        btn_eliminar_producto.setVisible(false);
        updateProductTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre_producto = new javax.swing.JTextField();
        combobox_categoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        precio_producto = new javax.swing.JTextField();
        btn_insertar_productos = new javax.swing.JButton();
        txt_codigo_producto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_modificar_producto = new javax.swing.JButton();
        btn_eliminar_producto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_PNG64/arrows_square_left.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos en existencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Categoria", "Producto", "Descripción", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla_productos.setGridColor(new java.awt.Color(153, 255, 255));
        tabla_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_productosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_productos);
        tabla_productos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tabla_productos.getColumnModel().getColumnCount() > 0) {
            tabla_productos.getColumnModel().getColumn(0).setResizable(false);
            tabla_productos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel2.setText("Nombre del producto*");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel5.setText("Categoria*");

        combobox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_categoriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setText("Descripción*");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane2.setViewportView(txt_descripcion);

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel4.setText("Precio por unidad*");

        btn_insertar_productos.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        btn_insertar_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_PNG64/arrows_circle_plus.png"))); // NOI18N
        btn_insertar_productos.setText("Agregar");
        btn_insertar_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertar_productosActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo:");

        btn_modificar_producto.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        btn_modificar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/software_pencil.png"))); // NOI18N
        btn_modificar_producto.setText("Editar");
        btn_modificar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_productoActionPerformed(evt);
            }
        });

        btn_eliminar_producto.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        btn_eliminar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_PNG 64/basic_trashcan.png"))); // NOI18N
        btn_eliminar_producto.setText("Elminar");
        btn_eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_productoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_PNG64/arrows_rotate.png"))); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precio_producto)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_insertar_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_modificar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(137, 137, 137))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox_categoria)
                    .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precio_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar_productos)
                    .addComponent(btn_eliminar_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(btn_modificar_producto))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addContainerGap(517, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_categoriaActionPerformed

    private void tabla_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_productosMouseClicked
        // TODO add your handling code here:
        
        int filaSeleccionada = tabla_productos.getSelectedRow();
        
        if (filaSeleccionada != -1) {
        int codigo = (int) tabla_productos.getValueAt(filaSeleccionada, 0);
        var categoria = (String) tabla_productos.getValueAt(filaSeleccionada, 1);
        var nombreProducto = (String) tabla_productos.getValueAt(filaSeleccionada, 2);
        var descripcion = (String) tabla_productos.getValueAt(filaSeleccionada, 3);
        double precio = (double) tabla_productos.getValueAt(filaSeleccionada, 4);

        // Llenar los campos con los datos de la fila seleccionada
        txt_codigo_producto.setText(Integer.toString(codigo));
        txt_nombre_producto.setText(nombreProducto);
        combobox_categoria.setSelectedItem(categoria);
        txt_descripcion.setText(descripcion);
        precio_producto.setText(String.valueOf(precio));
        
        btn_insertar_productos.setVisible(false);
        btn_modificar_producto.setVisible(true);
        btn_eliminar_producto.setVisible(true);
        txt_codigo_producto.setEditable(false);
        }
    }//GEN-LAST:event_tabla_productosMouseClicked

    private void btn_insertar_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertar_productosActionPerformed
        // TODO add your handling code here:
        
            String nombreProducto = txt_nombre_producto.getText();
            String descripcion = txt_descripcion.getText();
            String categoria = combobox_categoria.getSelectedItem().toString();
            String precio = precio_producto.getText();
            Conexion conexion = null;
            
            
            if (nombreProducto.isEmpty() || descripcion.isEmpty() || categoria.isEmpty() || precio.isEmpty()){
                JOptionPane.showMessageDialog(null, "Todos los campos son requerido");
            } else {
               try {
                
                // coonectando a la base de datos
                conexion = new Conexion("sa", "uma", "jdbc:sqlserver://localhost:1433;databaseName=CoffeShop;encrypt=false;trustServerCertificate=true;");
                conexion.conectar();

                // insertando a la BD
                String insertQuery = "INSERT INTO producto (id_categoria, nombre_producto, descripcion, precio) VALUES ((SELECT id_categoria FROM categoria WHERE nombre_categoria = ?), ?, ?, ?)";
                try (PreparedStatement preparedStatement = conexion.prepareStatement(insertQuery)) {
                    preparedStatement.setString(1, categoria);
                    preparedStatement.setString(2, nombreProducto);
                    preparedStatement.setString(3, descripcion);
                    preparedStatement.setFloat(4, Float.parseFloat(precio));

                    int affectedRows = preparedStatement.executeUpdate();
                    if (affectedRows > 0) {
                        JOptionPane.showMessageDialog(null, "Producto agregado correctamente.");
                        limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al agregar el producto.");
                    }
                }

                // Actuallizando la Jtable
                updateProductTable();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                 conexion.desconectar();
            }
        }
    }

        // metodo para actualizar la tabla 
        private void updateProductTable() {
            try {
                Conexion conexion = new Conexion("sa", "uma", "jdbc:sqlserver://localhost:1433;databaseName=CoffeShop;encrypt=false;trustServerCertificate=true;");
                conexion.conectar();

                String query = "SELECT p.id_producto, c.nombre_categoria, p.nombre_producto, p.descripcion, p.precio FROM producto p JOIN categoria c ON p.id_categoria = c.id_categoria";
                try (ResultSet resultSet = conexion.getStatement().executeQuery(query)) {
                    // llenando la jtable
                    DefaultTableModel model = (DefaultTableModel) tabla_productos.getModel();
                    model.setRowCount(0);

                    while (resultSet.next()) {
                        Object[] row = {
                            resultSet.getInt("id_producto"),  
                            resultSet.getString("nombre_categoria"),  
                            resultSet.getString("nombre_producto"), 
                            resultSet.getString("descripcion"),  // 
                            resultSet.getDouble("precio"),
                        };
                        model.addRow(row);
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                if(conexion != null) {
                conexion.desconectar();
                }
            }
    }//GEN-LAST:event_btn_insertar_productosActionPerformed

    
    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        frm_inicio frm_inicio = new frm_inicio();
        frm_inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_modificar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_productoActionPerformed
        // TODO add your handling code here:
            String codigo = txt_codigo_producto.getText();
            String nombreProducto = txt_nombre_producto.getText();
            String descripcion = txt_descripcion.getText();
            String categoria = combobox_categoria.getSelectedItem().toString();
            String precio = precio_producto.getText();
            Conexion conexion = null;
            
            
            if (nombreProducto.isEmpty() || descripcion.isEmpty() || categoria.isEmpty() || precio.isEmpty()){
                JOptionPane.showMessageDialog(null, "Todos los campos son requerido");
            } else {
               try {
                
                // coonectando a la base de datos
                conexion = new Conexion("sa", "uma", "jdbc:sqlserver://localhost:1433;databaseName=CoffeShop;encrypt=false;trustServerCertificate=true;");
                conexion.conectar();

                // insertando a la BD
                    String updateQuery = "UPDATE producto SET id_categoria = (SELECT id_categoria FROM categoria WHERE nombre_categoria = ?), nombre_producto = ?, descripcion = ?, precio = ? WHERE id_producto = ?";
                    try (PreparedStatement preparedStatement = conexion.prepareStatement(updateQuery)) {
                        preparedStatement.setString(1, categoria); // Aquí obtienes el id_categoria correspondiente al nombre de la categoría
                        preparedStatement.setString(2, nombreProducto);
                        preparedStatement.setString(3, descripcion);
                        preparedStatement.setFloat(4, Float.parseFloat(precio));
                        preparedStatement.setString(5, codigo); // Aquí utilizas el id_producto

                    int affectedRows = preparedStatement.executeUpdate();
                    if (affectedRows > 0) {
                        JOptionPane.showMessageDialog(null, "Producto actualizado correctamente.");
                        btn_modificar_producto.setVisible(false);
                        btn_eliminar_producto.setVisible(false);
                        limpiarCampos();
                        btn_insertar_productos.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al actualizar el producto.");
                    }
                }

                // Actuallizando la Jtable
                updateProductTable();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            } finally {
                 conexion.desconectar();
            }
        }
        
    }//GEN-LAST:event_btn_modificar_productoActionPerformed

    private void btn_eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_productoActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txt_codigo_producto.getText());
        
        conexion = new Conexion("sa", "uma", "jdbc:sqlserver://localhost:1433;databaseName=CoffeShop;encrypt=false;trustServerCertificate=true;");
        conexion.conectar();
        
        String deleteQuery = "DELETE FROM producto WHERE id_producto = "+codigo+";";
            
        try {
            PreparedStatement preparedStatement = conexion.prepareStatement(deleteQuery);
            
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
            
            limpiarCampos();
            updateProductTable();
            btn_modificar_producto.setVisible(false);
            btn_eliminar_producto.setVisible(false);
            btn_insertar_productos.setVisible(true);
           
                        
        } catch (SQLException ex) {
            Logger.getLogger(frm_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_eliminar_productoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        btn_modificar_producto.setVisible(false);
        btn_eliminar_producto.setVisible(false);
        btn_insertar_productos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void limpiarCampos() {
    txt_codigo_producto.setText("");
    txt_nombre_producto.setText("");
    combobox_categoria.setSelectedItem("");
    txt_descripcion.setText("");
    precio_producto.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_productos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_producto;
    private javax.swing.JButton btn_insertar_productos;
    private javax.swing.JButton btn_modificar_producto;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> combobox_categoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField precio_producto;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField txt_codigo_producto;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_nombre_producto;
    // End of variables declaration//GEN-END:variables
}
