/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffeshoppp.vistas;

import coffeshoppp.modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import coffeshoppp.modelo.Sesion;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


/**
 *
 * @author MINEDUCYT
 */
public class frm_register extends javax.swing.JFrame {

    /**
     * Creates new form frm_register
     */
    public frm_register() {
        initComponents();
        
        txt_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Cocinero", "Cajero" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_usuario_name = new javax.swing.JTextField();
        txt_register_password = new javax.swing.JPasswordField();
        txt_re_registerPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_combobox = new javax.swing.JComboBox<>();
        btn_register = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_go_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRA NUEVO USUARIO");

        jLabel2.setText("Nombres*");

        jLabel3.setText("Apellidos*");

        jLabel4.setText("Nombre de usuario*");

        txt_re_registerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_re_registerPassActionPerformed(evt);
            }
        });

        jLabel5.setText("Contraseña*");

        jLabel6.setText("Verifica nuevamente tu contraseña*");

        jLabel7.setText("Tipo de usuario*");

        txt_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Usa una combinacion de mayusculas y caracteres alfanúmericos*");

        btn_go_login.setText("Ya tengo una cuenta, iniciar sesión");
        btn_go_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_go_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(170, 170, 170))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(txt_usuario_name, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txt_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txt_re_registerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_apellido)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)
                                        .addComponent(txt_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_go_login)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txt_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_re_registerPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_go_login)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_re_registerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_re_registerPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_re_registerPassActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
            // TODO add your handling code here:
            String nombres = txt_nombre.getText();
            String apellidos = txt_apellido.getText();
            String nombre_usuario = txt_usuario_name.getText();
            String passRegister = new String(txt_register_password.getPassword());
            String passVerification = new String(txt_re_registerPass.getPassword());
            String rol = txt_combobox.getSelectedItem().toString();

            if (nombres.isEmpty() || apellidos.isEmpty() || nombre_usuario.isEmpty() || passRegister.isEmpty() || passVerification.isEmpty() || rol.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
            } else {
                try {
                    //validacion de compobacion de contraseña segura
                    String passSegura = "^(?=.*[A-Z])(?=.*\\d).{8,}$";
                    if (!passRegister.matches(passSegura)) {
                    JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 8 caracteres, incluyendo al menos una mayúscula y un número");
                    return; // Salir del método sin continuar con el registro
                    }
                    if (passRegister.equals(passVerification)) {
   
                        Conexion conexion = new Conexion("sa", "uma", "jdbc:sqlserver://localhost:1433;databaseName=CoffeShop;encrypt=false;trustServerCertificate=true;");

                        try {
                            
                            String hashedPassword = hashPassword(passRegister);
                            
                            conexion.conectar();
                            Connection connection = conexion.getConnection();

                            if (connection != null) {
                                String query = "INSERT INTO usuario (nombre, apellido, login, contrasenia, id_rol)"
                                        + " VALUES (?, ?, ?, ?, (SELECT id_rol FROM rol WHERE nombre_rol = ?))";

                                try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                                        preparedStatement.setString(1, nombres);
                                        preparedStatement.setString(2, apellidos);
                                        preparedStatement.setString(3, nombre_usuario);
                                        preparedStatement.setString(4, hashedPassword);
                                        preparedStatement.setString(5, rol);

                                    int result = preparedStatement.executeUpdate();

                                    if (result > 0) {
                                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                                        frm_login frm_login = new frm_login();
                                        frm_login.setVisible(true);
                                        this.setVisible(false);
                                    } else {
                                        clearFormFields();
                                        JOptionPane.showMessageDialog(null, "Error al registrar el usuario. Por favor, inténtalo nuevamente");
                                    }
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Error al conectarse con la base de datos");
                            }
                        } catch (NoSuchAlgorithmException ex){
                            ex.printStackTrace();
                        } finally {
                            conexion.desconectar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden. Inténtalo de nuevo");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al registrar el usuario. Por favor, inténtalo nuevamente");
                }
            }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_go_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_go_loginActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Ya tienes una cuenta?", "Regresar al inicio de sesión", JOptionPane.YES_NO_OPTION);
        
            if (opcion == JOptionPane.YES_OPTION) {
                // Abre la ventana de inicio de sesión nuevamente o realiza otras acciones necesarias
                frm_login frm_login = new frm_login();
                frm_login.setVisible(true);
                this.setVisible(false);
            } else {
                // Si el usuario hace clic en "No", no se realiza ninguna acción adicional
            }
    }//GEN-LAST:event_btn_go_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Función para aplicar el hash SHA-256 a la contraseña
    private String hashPassword(String password) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashedBytes = md.digest(password.getBytes());

        // Convertir bytes a representación hexadecimal
        StringBuilder sb = new StringBuilder();
        for (byte b : hashedBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }
    
    private void clearFormFields() {
    txt_nombre.setText("");
    txt_apellido.setText("");
    txt_usuario_name.setText("");
    txt_register_password.setText("");
    txt_re_registerPass.setText("");
    txt_combobox.setSelectedIndex(0);
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_register().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_go_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JComboBox<String> txt_combobox;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_re_registerPass;
    private javax.swing.JPasswordField txt_register_password;
    private javax.swing.JTextField txt_usuario_name;
    // End of variables declaration//GEN-END:variables
}
